### PR TITLE
config: Add configuration using statefulset

### PR DESCRIPTION
**Pull request by avisiedo**
- Update role for using Statefulset objects.
- Add persistent volume configuration.
- Add hostpath configuration.
- Add ephimeral configuration.
    
Signed-off-by: Alejandro Visiedo <avisiedo@redhat.com>

### CODE REVIEW

**Comment by frasertweedale** [comment]
@avisiedo this PR does not handle the OCP_NAMESPACE env var.  Namespace is hardcoded as `freeipa`.  So we should address that before merge.

Also, the file path says `statefullset`, but it should be `statefulset` (one `l`).  This is not a showstopper, but if we have to make some changes so it should be easy to fix.

**Comment by frasertweedale** [comment]
When creating, I get following error from `oc describe statefulset/freeipa`:
```
  Warning  FailedCreate  8m47s (x22 over 41m)  statefulset-controller  create Claim freeipa-freeipa-0 for Pod freeipa-0 in StatefulSet freeipa failed error: PersistentVolumeClaim "freeipa-freeipa-0" is invalid: spec.accessModes: Required value: at least 1 access mode is required
```

I think this is a typo, one liner-fix `accessMode` -> `accessModes`.

**Comment by frasertweedale** [comment]
With the type fix from aforementioned comment, the Pod gets created successfully, but cannot execute due to PVC related error:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  49s   default-scheduler  0/6 nodes are available: 6 persistentvolumeclaim "freeipa" not found.
  Warning  FailedScheduling  48s   default-scheduler  0/6 nodes are available: 6 persistentvolumeclaim "freeipa" not found.
[f33-3:~/dev/freeipa-kustomize] [ pull/4● ] ftweedal% oc get pvc
NAME                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
freeipa-freeipa-0   Pending                                      standard       62s
```

The pvc created via the StatefulSet has name `freeipa-freeipa-0`, but the claim name the pod is trying to use is `freeipa`.

**Comment by frasertweedale** [comment]
Two commits that fix minor issues: 

- https://github.com/freeipa/freeipa-kustomize/commit/fe403f9d4f3b0ae14b7c9c83d6636d8a0c4bef4c
- https://github.com/freeipa/freeipa-kustomize/commit/ca5a968fde0919e00eb0031c47862699fea7d16a

**Comment by avisiedo** [comment]
Thanks @frasertweedale , I have realised more mistakes fixing the above.Now it has a better configuration. PR updated.

**Pull request merged**
